### ISSUE TITLE
Can't compile example Wattmeter

### ISSUE THREAD

**Issue by fran6t** [rkoptev/ACS712-arduino#1]
Hello
i have an error when i compile Wattmeter
i have placed  your package under my repertory Library
i open Example -> ACS712 -> Wattmeter
i run compile and i have this error

> /home/fran6t/Bureau/Dropbox/arduino-1.8.1-linux64/libraries/ACS712/ACS712.cpp: In function 'void setZeroPoint(int)':
> /home/fran6t/Bureau/Dropbox/arduino-1.8.1-linux64/libraries/ACS712/ACS712.cpp:33:2: error: 'zero' was not declared in this scope
>   zero = _zero;
>   ^
> exit status 1
> Erreur de compilation pour la carte Arduino Ethernet

I have try other card and older version of ide but sems error. 

Sorry for my bad english and for my bad level in C is it possible to give a way to correct my problem.
Thanking you in advance

**Comment by rkoptev** [comment]
Hi!
Thank you for pointing on this error. This was a bug on my side, and it has just been fixed. Thank you for your help!
