### ISSUE TITLE
VREF no puede ser 5v es un ESP8266

### ISSUE THREAD

**Issue by l337quez** [rkoptev/ACS712-arduino#13]
esta bien el esquematico que pones, sin embargo...dejas como VREF 5v, esto hace que nunca se pueda uasar la libreria con un esp, deberia haber una forma de decirle a la libreria que esta usando un ESP y que cambia la vref a 3.3v a demas seria bueno que hubiera una forma de meter los valores reales de las resistencias.. si las resistencias no son precisas el valor cambia.

**Comment by rkoptev** [comment]
@l337quez why not? VREF hardcoded in lib only to represent supply voltage of the sensor. But I agree that it's a crutch solution.

Anyway, are you expecting any issues with ESP? Or you just assuming?

**Comment by l337quez** [comment]
la mejor opcion es usar un convertidor de niveles

**Comment by l337quez** [comment]
The NodeMCU works with a reference voltage of 1v. That is, when you convert analog to digital it cannot be 5/1023, because the reference is not 5, the reference is 1v. It's not even 3.3, I thought it was 3.3

**Comment by mso1985** [comment]
Esta libreria, con wemos d1 pro mini (con divisor de voltage) funciona muy bien, tiene un error de 0.2A  con un acs712 de 30A
