### ISSUE TITLE
nodemcu v3 support ?

### ISSUE THREAD

**Issue by igerko** [rkoptev/ACS712-arduino#2]
Hi,

is it possible to use this library with 3.3 ADC on NodeMCU v3? It's working with my Nano, but MCU gives me strange values

**Comment by rkoptev** [comment]
Hi Jakub!

Yes, It's possible to use this library with NodeMCU and other ESP8266 based boards!
But keep in mind few important things:
1. ACS712 sensor needs 5V on VCC pin, so you need step up DC-DC converter to power on it.
2. ESP8266's ADC works in range 0-1 Volts, it means you need to use voltage divider to convert 0-5V range from sensor to 0-1V.
