### ISSUE TITLE
How to change frequency from the default 50 to 60?

### ISSUE THREAD

**Issue by N-P-S** [rkoptev/ACS712-arduino#21]
Hi, our electricity mains is in 60hz. I'm not sure how to change it from the default 50hz.
is this correct? "sensor.getCurrentAC(60);"  or by this, "#define DEFAULT_FREQUENCY 60"?

Sorry, I am new to programming. thank you

**Comment by Yarce008** [comment]
hola yo tengo el mismo problema , lograste solucionarlo  ?

**Comment by rkoptev** [comment]
> Hi, our electricity mains is in 60hz. I'm not sure how to change it from the default 50hz. is this correct? "sensor.getCurrentAC(60);" or by this, "#define DEFAULT_FREQUENCY 60"?
> 
> Sorry, I am new to programming. thank you

Use the 1st option
