### ISSUE TITLE
nodemcu v 1.0(ESP-12E module) supports? 

### ISSUE THREAD

**Issue by Nikitha-Kondapalli** [rkoptev/ACS712-arduino#3]
I am trying to measure AC current using the following code. This code works fine with Arduino but not with nodemcu v 1.0. Even if the bulb is off, we are getting a power in between 7 to 8 Watts. and When it is on we are getting a power of more than 30 Watts.

Code is as follows:

/*
  This example shows how to measure the power consumption
  of devices in 230V electrical system
  or any other system with alternative current
*/

// We have 30 amps version sensor connected to A1 pin of arduino
// Replace with your version if necessary
int i;
int32_t zero;
long previous=0;
float e=0;
float energy;
float x;
void setup() 
{
   Serial.begin(9600);
    zero=0;
    for(i=0;i<10;i++){
        zero=zero+analogRead(A0);
 
        delay(10);
  }
    zero=zero/10;
   digitalWrite(2,HIGH);
   Serial.print("zero :");
   Serial.println(zero);
  // This method calibrates zero point of sensor,
  // It is not necessary, but may positively affect the accuracy
  // Ensure that no current flows through the sensor at this moment
}

void loop() {
  // We use 230V because it is the common standard in European countries
  // Change to your local, if necessary
 
  float V = 230;
  uint32_t period = 1000000 / 50;
  uint32_t t_start = micros();
 // Serial.print("t_start:");
  //Serial.prin tln(t_start);
  uint32_t Isum = 0, measurements_count = 0;
  int32_t Inow;
  while (micros() - t_start < period) {
    //Serial.print("time:");
    //Serial.println(micros()-t_start)
    Inow = zero-analogRead(A0);
    Isum += Inow*Inow;
    measurements_count++;
  }
  float Irms = sqrt(Isum / measurements_count) / 1023 * 5.0 / 0.185;
  Serial.print("Irms:");
  Serial.println(Irms);
  // To measure current we need to know the frequency of current
  // By default 50Hz is used, but you can specify own, if necessary
  

  // To calculate the power we need voltage multiplied by current
  float P = V * Irms;
  if(digitalRead(2)==HIGH)
  {
    long now=millis();
    if(now-previous >=2000)
     x= 2.0/3600.0;
    e= e+ P*x;
    energy =e/1000.0;
  }

 Serial.println(String("P = ") + P + " Watts");
 Serial.println(energy,6);

  delay(1000);
}

**Comment by rkoptev** [comment]
I do not know why you mixed the source code of the library with examples, but in that case I can not guarantee that your code will work. Since these sensors are analog - there may be an error in the measurement. To eliminate this error, use the zero point calibration. This is described in the examples.
