### ISSUE TITLE
Pls. correct  "Error compiling for board NodeMCU 1.0 (ESP-12E Module)"

### ISSUE THREAD

**Issue by pico563** [rkoptev/ACS712-arduino#6]
WARNING: library ACS712-arduino-master claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
C:\Users\Documents\Arduino\libraries\ACS712-arduino-master\src\ACS712.cpp:46:51: error: default argument given for parameter 1 of 'float ACS712::getCurrentAC(uint16_t)' [-fpermissive]

 float ACS712::getCurrentAC(uint16_t frequency = 50) {

                                                   ^

In file included from C:\Users\Documents\Arduino\libraries\ACS712-arduino-master\src\ACS712.cpp:1:0:

C:\Users\Documents\Arduino\libraries\ACS712-arduino-master\src\ACS712.h:19:8: error: after previous specification in 'float ACS712::getCurrentAC(uint16_t)' [-fpermissive]

  float getCurrentAC(uint16_t frequency = 50);

        ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by rkoptev** [comment]
Thank you for reporting, it's fixed now.
