### ISSUE TITLE
ACS712 with ADS1115

### ISSUE THREAD

**Issue by pcmarcon** [rkoptev/ACS712-arduino#8]
Hi Ruslan,
Is it possible to use Your lib together with Analog to Digital converter like ADS1115?
Thanks in Advance,
Paulo

**Comment by rkoptev** [comment]
Hi Paulo,

Currently this library don't have opportunity to work with external ADCs. You are already the second person interested in this functionality, so maybe it will be added in the future. However, at the moment there is no such possibility.

**Comment by pcmarcon** [comment]
OK. Thanks anyway!

**Comment by chinswain** [comment]
+1
